### ISSUE TITLE
Gráfico errado sendo gerado na seção 5.3.2 do pdf

### ISSUE THREAD

**Issue by adrianodennanni** [net-map/monografia#2]
Ao invés do gráfico de NN, está aparecendo o gráfico do KNN, e fora do lugar que deveria aparecer.
![image](https://cloud.githubusercontent.com/assets/5194315/20515201/9bad8b48-b077-11e6-881d-e77ce11b047c.png)

**Comment by ThiagoLira** [comment]
DONE
